USE DATABASE GRAMMY_ANALYSIS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE GRAMMY_WINNER_DATA (
    YEAR INT,
    CEREMONY_NUMBER INT,
    DECADE INT,
    ERA VARCHAR(50),
    CATEGORY VARCHAR(50),
    AWARD_GROUP VARCHAR(10),
    WINNER VARCHAR(255),
    ARTIST VARCHAR(400),
    STATUS VARCHAR(10),
    TOTAL_WINS INT,
    CATEGORY_TOTAL_WINNERS INT,
    DATA_SOURCE VARCHAR(20),
    COLLECTION_DATE DATE
);


COPY INTO GRAMMY_WINNER_DATA
    FROM @s3data_stage
        FILES = ('Grammy_Awards_Winners_20260208_055452.csv');